# Source: cluster-api-aws/templates/job-post.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: 708b66f7-bb92-449c-b966-db475eb592de-capi-aws-post
  namespace: 708b66f7-bb92-449c-b966-db475eb592de
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: 708b66f7-bb92-449c-b966-db475eb592de-capi-aws
    spec:
      serviceAccountName: 708b66f7-bb92-449c-b966-db475eb592de-capi-aws
      containers:
      - name: generate-worker-machines
        image: "ghcr.io/openinfradev/python_kubectl_argo:v1.1.0"
        imagePullPolicy: IfNotPresent
        command:
        - timeout
        - 20m
        - /generate_worker_machines.py
        - 708b66f7-bb92-449c-b966-db475eb592de
        - 708b66f7-bb92-449c-b966-db475eb592de
        volumeMounts:
        - name: vol
          subPath: mp.raw.yaml
          mountPath: /mp.raw.yaml
        - name: vol
          subPath: md.raw.yaml
          mountPath: /md.raw.yaml
        - name: vol
          subPath: generate_worker_machines.py
          mountPath: /generate_worker_machines.py

      volumes:
      - name: vol
        configMap:
          name: 708b66f7-bb92-449c-b966-db475eb592de-capi-aws
          defaultMode: 0555
      restartPolicy: OnFailure
