# Source: cluster-api-aws/templates/job-check.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: 708b66f7-bb92-449c-b966-db475eb592de-capi-aws-check
  namespace: 708b66f7-bb92-449c-b966-db475eb592de
spec:
  template:
    metadata:
      name: 708b66f7-bb92-449c-b966-db475eb592de-capi-aws
    spec:
      serviceAccountName: 708b66f7-bb92-449c-b966-db475eb592de-capi-aws
      containers:
      - name: wait-for-ready
        image: "ghcr.io/openinfradev/python_kubectl_argo:v1.1.0"
        imagePullPolicy: IfNotPresent
        command:
        - timeout 
        - 5m
        - /wait_for_kubeconfig.sh  
        - 708b66f7-bb92-449c-b966-db475eb592de
        - 708b66f7-bb92-449c-b966-db475eb592de
        volumeMounts:
        - name: vol
          subPath: wait_for_kubeconfig.sh
          mountPath: /wait_for_kubeconfig.sh
      volumes:
      - name: vol
        configMap:
          name: 708b66f7-bb92-449c-b966-db475eb592de-capi-aws
          defaultMode: 0555
      restartPolicy: OnFailure
