# Source: cluster-api-aws/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: 708b66f7-bb92-449c-b966-db475eb592de-capi-aws
  namespace: 708b66f7-bb92-449c-b966-db475eb592de
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: 708b66f7-bb92-449c-b966-db475eb592de-capi-aws
subjects:
- kind: ServiceAccount
  name: 708b66f7-bb92-449c-b966-db475eb592de-capi-aws
